/* Automatically generated by po2tbl.sed from kbd.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"openvt: %s: illegal vt number\n", 2},
  {"openvt: only root can use the -u flag.\n", 3},
  {"Couldnt get a file descriptor referring to the console\n", 4},
  {"openvt: cannot find a free vt\n", 5},
  {"openvt: cannot check whether vt %d is free\n", 6},
  {"        use `openvt -f' to force.\n", 7},
  {"openvt: vt %d is in use; command aborted\n", 8},
  {"openvt: Unable to open %s: %s\n", 9},
  {"openvt: Cannot open %s read/write (%s)\n", 10},
  {"openvt: using VT %s\n", 11},
  {"openvt: Unable to set new session (%s)\n", 12},
  {"\
\n\
openvt: could not open %s R/W (%s)\n", 13},
  {"openvt: could not deallocate console %d\n", 14},
  {"usage: chvt N\n", 15},
  {"%s: unknown option\n", 16},
  {"%s: deallocating all unused consoles failed\n", 17},
  {"%s: 0: illegal VT number\n", 18},
  {"%s: VT 1 is the console and cannot be deallocated\n", 19},
  {"%s: could not deallocate console %d\n", 20},
  {"KDGKBENT error at index 0 in table %d\n", 21},
  {"%s: cannot find any keymaps?\n", 22},
  {"%s: plain map not allocated? very strange ...\n", 23},
  {"KDGKBENT error at index %d in table %d\n", 24},
  {"keycode range supported by kernel:           1 - %d\n", 25},
  {"max number of actions bindable to a key:         %d\n", 26},
  {"number of keymaps in actual use:                 %d\n", 27},
  {"of which %d dynamically allocated\n", 28},
  {"ranges of action codes supported by kernel:\n", 29},
  {"number of function keys supported by kernel: %d\n", 30},
  {"max nr of compose definitions: %d\n", 31},
  {"nr of compose definitions in actual use: %d\n", 32},
  {"\
Symbols recognized by %s:\n\
(numeric value, symbol)\n\
\n", 33},
  {"\
\n\
The following synonyms are recognized:\n\
\n", 34},
  {"%-15s for %s\n", 35},
  {"\
\n\
Recognized modifier names and their column numbers:\n", 36},
  {"# not alt_is_meta: on keymap %d key %d is bound to", 37},
  {"impossible: not meta?\n", 38},
  {"KDGKBSENT failed at index %d: ", 39},
  {"dumpkeys version %s", 40},
  {"\
\n\
usage: dumpkeys [options...]\n\
\n\
valid options are:\n\
\n\
\t-h --help\t    display this help text\n\
\t-i --short-info\t    display information about keyboard driver\n\
\t-l --long-info\t    display above and symbols known to loadkeys\n\
\t-n --numeric\t    display keytable in hexadecimal notation\n\
\t-f --full-table\t    don't use short-hand notations, one row per keycode\n\
\t-1 --separate-lines one line per (modifier,keycode) pair\n\
\t   --funcs-only\t    display only the function key strings\n\
\t   --keys-only\t    display only key bindings\n\
\t   --compose-only   display only compose key combinations\n\
\t-c --charset=", 41},
  {"\
\t\t\t    interpret character action codes to be from the\n\
\t\t\t    specified character set\n", 42},
  {"\
%s version %s\n\
\n\
Usage: %s [options]\n\
\n\
Valid options are:\n\
\n\
\t-h --help            display this help text\n\
\t-V --version         display this help text\n\
\t-n --next-available  display next unallocated VT\n", 43},
  {"Couldn't read VTNO: ", 44},
  {"error executing  %s\n", 45},
  {"Couldnt open %s\n", 46},
  {"usage: getkeycodes\n", 47},
  {"Plain scancodes xx (hex) versus keycodes (dec)\n", 48},
  {"0 is an error; for 1-88 (0x01-0x58) scancode equals keycode\n", 49},
  {"for 1-%d (0x01-0x%02x) scancode equals keycode\n", 50},
  {"\
\n\
\n\
Escaped scancodes e0 xx (hex)\n", 51},
  {"failed to get keycode for scancode 0x%x\n", 52},
  {"\
Usage:\n\
\t%s [-s] [-C console]\n", 53},
  {"usage: kbd_mode [-a|-u|-k|-s]\n", 54},
  {"kbd_mode: error reading keyboard mode\n", 55},
  {"The keyboard is in raw (scancode) mode\n", 56},
  {"The keyboard is in mediumraw (keycode) mode\n", 57},
  {"The keyboard is in the default (ASCII) mode\n", 58},
  {"The keyboard is in Unicode (UTF-8) mode\n", 59},
  {"The keyboard is in some unknown mode\n", 60},
  {"%s: error setting keyboard mode\n", 61},
  {"Typematic Rate set to %.1f cps (delay = %d ms)\n", 62},
  {"Usage: kbdrate [-V] [-s] [-r rate] [-d delay]\n", 63},
  {"Cannot open /dev/port", 64},
  {"bug: getfont called with count<256\n", 65},
  {"%s: out of memory\n", 66},
  {"unknown charset %s - ignoring charset request\n", 67},
  {"null symbol found", 68},
  {"assuming iso-8859-1 %s\n", 69},
  {"assuming iso-8859-15 %s\n", 70},
  {"assuming iso-8859-2 %s\n", 71},
  {"assuming iso-8859-3 %s\n", 72},
  {"assuming iso-8859-4 %s\n", 73},
  {"unknown keysym '%s'\n", 74},
  {"\
Usage:\n\
\t%s [-C console] [-o map.orig]\n", 75},
  {"Bad input line: %s\n", 76},
  {"%s: Glyph number (0x%x) larger than font length\n", 77},
  {"%s: Bad end of range (0x%x)\n", 78},
  {"%s: Bad Unicode range corresponding to font position range 0x%x-0x%x\n", 79},
  {"\
%s: Unicode range U+%x-U+%x not of the same length as font position range 0x%\
x-0x%x\n", 80},
  {"%s: trailing junk (%s) ignored\n", 81},
  {"Loading unicode map from file %s\n", 82},
  {"%s: %s: Warning: line too long\n", 83},
  {"\
%s: not loading empty unimap\n\
(if you insist: use option -f to override)\n", 84},
  {"entry", 85},
  {"entries", 86},
  {"Saved unicode map on `%s'\n", 87},
  {"Appended Unicode map\n", 88},
  {"usage: %s [-v] [-o map.orig] map-file\n", 89},
  {"mapscrn: cannot open map file _%s_\n", 90},
  {"Cannot stat map file", 91},
  {"Loading binary direct-to-font screen map from file %s\n", 92},
  {"Error reading map from file `%s'\n", 93},
  {"Loading binary unicode screen map from file %s\n", 94},
  {"Loading symbolic screen map from file %s\n", 95},
  {"Error parsing symbolic map from `%s', line %d\n", 96},
  {"Error writing map to file\n", 97},
  {"Cannot read console map\n", 98},
  {"Saved screen map in `%s'\n", 99},
  {"%s: short ucs2 unicode table\n", 100},
  {"%s: short utf8 unicode table\n", 101},
  {"%s: bad utf8\n", 102},
  {"%s: unknown utf8 error\n", 103},
  {"%s: short unicode table\n", 104},
  {"%s: Error reading input font", 105},
  {"%s: Bad call of readpsffont\n", 106},
  {"%s: Unsupported psf file mode (%d)\n", 107},
  {"%s: Unsupported psf version (%d)\n", 108},
  {"%s: zero input font length?\n", 109},
  {"%s: zero input character size?\n", 110},
  {"%s: Input file: bad input length (%d)\n", 111},
  {"%s: Input file: trailing garbage\n", 112},
  {"appendunicode: illegal unicode %u\n", 113},
  {"Cannot write font file header", 114},
  {"%s: Warning: line too long\n", 115},
  {"%s: Bad input line: %s\n", 116},
  {"%s: Glyph number (0x%lx) past end of font\n", 117},
  {"%s: Bad end of range (0x%lx)\n", 118},
  {"\
%s: Corresponding to a range of font positions, there should be a Unicode \
range\n", 119},
  {"\
Usage:\n\
\t%s infont intable outfont\n", 120},
  {"\
Usage:\n\
\t%s infont [outtable]\n", 121},
  {"\
Usage:\n\
\t%s infont outfont\n", 122},
  {"\
Usage:\n\
\t%s [-i infont] [-o outfont] [-it intable] [-ot outtable] [-nt]\n", 123},
  {"%s: Bad magic number on %s\n", 124},
  {"%s: psf file with unknown magic\n", 125},
  {"%s: input font does not have an index\n", 126},
  {"resizecons: cannot find videomode file %s\n", 127},
  {"Invalid number of lines\n", 128},
  {"Old mode: %dx%d  New mode: %dx%d\n", 129},
  {"Old #scanlines: %d  New #scanlines: %d  Character height: %d\n", 130},
  {"resizecons: the command `%s' failed\n", 131},
  {"\
resizecons: don't forget to change TERM (maybe to con%dx%d or linux-%dx%d)\n", 132},
  {"\
resizecons:\n\
call is:  resizecons COLSxROWS  or:  resizecons COLS ROWS\n\
or: resizecons -lines ROWS, with ROWS one of 25, 28, 30, 34, 36, 40, 44, 50, \
60\n", 133},
  {"resizecons: cannot get I/O permissions.\n", 134},
  {"usage: screendump [n]\n", 135},
  {"Error reading %s\n", 136},
  {"couldn't read %s, and cannot ioctl dump\n", 137},
  {"couldn't read %s\n", 138},
  {"Strange ... screen is both %dx%d and %dx%d ??\n", 139},
  {"Error writing screendump\n", 140},
  {"\
Usage: setfont [write-options] [-<N>] [newfont..] [-m consolemap] [-u \
unicodemap]\n\
  write-options (take place before file loading):\n\
    -o  <filename>  Write current font to <filename>\n\
    -O  <filename>  Write current font and unicode map to <filename>\n\
    -om <filename>  Write current consolemap to <filename>\n\
    -ou <filename>  Write current unicodemap to <filename>\n\
If no newfont and no -[o|O|om|ou|m|u] option is given,\n\
a default font is loaded:\n\
    setfont         Load font \"default[.gz]\"\n\
    setfont -<N>    Load font \"default8x<N>[.gz]\"\n\
The -<N> option selects a font from a codepage that contains three fonts:\n\
    setfont -{8|14|16} codepage.cp[.gz]   Load 8x<N> font from codepage.cp\n\
Explicitly (with -m or -u) or implicitly (in the fontfile) given mappings\n\
will be loaded and, in the case of consolemaps, activated.\n\
    -h<N>      (no space) Override font height.\n\
    -m <fn>    Load console screen map.\n\
    -u <fn>    Load font unicode map.\n\
    -m none    Suppress loading and activation of a screen map.\n\
    -u none    Suppress loading of a unicode map.\n\
    -v         Be verbose.\n\
    -C <cons>  Indicate console device to be used.\n\
    -V         Print version and exit.\n\
Files are loaded from the current directory or /usr/lib/kbd/*/.\n", 141},
  {"setfont: too many input files\n", 142},
  {"\
setfont: cannot both restore from character ROM and from file. Font \
unchanged.\n", 143},
  {"Bad character height %d\n", 144},
  {"Bad character width %d\n", 145},
  {"%s: font position 32 is nonblank\n", 146},
  {"%s: wiped it\n", 147},
  {"%s: background will look funny\n", 148},
  {"Loading %d-char %dx%d font from file %s\n", 149},
  {"Loading %d-char %dx%d font\n", 150},
  {"Loading %d-char %dx%d (%d) font from file %s\n", 151},
  {"Loading %d-char %dx%d (%d) font\n", 152},
  {"%s: bug in do_loadtable\n", 153},
  {"Loading Unicode mapping table...\n", 154},
  {"Cannot open font file %s\n", 155},
  {"When loading several fonts, all must be psf fonts - %s isn't\n", 156},
  {"Read %d-char %dx%d font from file %s\n", 157},
  {"When loading several fonts, all must have the same height\n", 158},
  {"When loading several fonts, all must have the same width\n", 159},
  {"Cannot find default font\n", 160},
  {"Cannot find %s font\n", 161},
  {"Reading font file %s\n", 162},
  {"No final newline in combine file\n", 163},
  {"Too many files to combine\n", 164},
  {"Hmm - a font from restorefont? Using the first half.\n", 165},
  {"Bad input file size\n", 166},
  {"\
This file contains 3 fonts: 8x8, 8x14 and 8x16. Please indicate\n\
using an option -8 or -14 or -16 which one you want loaded.\n", 167},
  {"You asked for font size %d, but only 8, 14, 16 are possible here.\n", 168},
  {"Found nothing to save\n", 169},
  {"Cannot write font file", 170},
  {"Saved %d-char %dx%d font file on %s\n", 171},
  {"\
usage: setkeycode scancode keycode ...\n\
 (where scancode is either xx or e0xx, given in hexadecimal,\n\
  and keycode is given in decimal)\n", 172},
  {"even number of arguments expected", 173},
  {"error reading scancode", 174},
  {"code outside bounds", 175},
  {"failed to set scancode %x to keycode %d\n", 176},
  {"\
Usage:\n\
\tsetleds [-v] [-L] [-D] [-F] [[+|-][ num | caps | scroll %s]]\n\
Thus,\n\
\tsetleds +caps -num\n\
will set CapsLock, clear NumLock and leave ScrollLock unchanged.\n\
The settings before and after the change (if any) are reported\n\
when the -v option is given or when no change is requested.\n\
Normally, setleds influences the vt flag settings\n\
(and these are usually reflected in the leds).\n\
With -L, setleds only sets the leds, and leaves the flags alone.\n\
With -D, setleds sets both the flags and the default flags, so\n\
that a subsequent reset will not change the flags.\n", 177},
  {"on ", 178},
  {"off", 179},
  {"Error reading current led setting. Maybe stdin is not a VT?\n", 180},
  {"\
Error reading current flags setting. Maybe you are not on the console?\n", 181},
  {"Error reading current led setting from /dev/kbd.\n", 182},
  {"KIOCGLED unavailable?\n", 183},
  {"KIOCSLED unavailable?\n", 184},
  {"Error opening /dev/kbd.\n", 185},
  {"Error resetting ledmode\n", 186},
  {"Current default flags:  ", 187},
  {"Current flags:          ", 188},
  {"Current leds:           ", 189},
  {"\
unrecognized argument: _%s_\n\
\n", 190},
  {"Old default flags:    ", 191},
  {"New default flags:    ", 192},
  {"Old flags:            ", 193},
  {"New flags:            ", 194},
  {"Old leds:             ", 195},
  {"New leds:             ", 196},
  {"\
Usage:\n\
\tsetmetamode [ metabit | meta | bit | escprefix | esc | prefix ]\n\
Each vt has his own copy of this bit. Use\n\
\tsetmetamode [arg] < /dev/ttyn\n\
to change the settings of another vt.\n\
The setting before and after the change are reported.\n", 197},
  {"Meta key sets high order bit\n", 198},
  {"Meta key gives Esc prefix\n", 199},
  {"Strange mode for Meta key?\n", 200},
  {"Error reading current setting. Maybe stdin is not a VT?\n", 201},
  {"old state:    ", 202},
  {"new state:    ", 203},
  {"usage: %s\n", 204},
  {"failed to restore original translation table\n", 205},
  {"failed to restore original unimap\n", 206},
  {"cannot change translation table\n", 207},
  {"%s: out of memory?\n", 208},
  {"\
usage: showconsolefont [-v|-V]\n\
(probably after loading a font with `setfont font')\n", 209},
  {"?UNKNOWN?", 210},
  {"kb mode was %s\n", 211},
  {"\
[ if you are trying this under X, it might not work\n\
since the X server is also reading /dev/console ]\n", 212},
  {"caught signal %d, cleaning up...\n", 213},
  {"\
showkey version %s\n\
\n\
usage: showkey [options...]\n\
\n\
valid options are:\n\
\n\
\t-h --help\tdisplay this help text\n\
\t-a --ascii\tdisplay the decimal/octal/hex values of the keys\n\
\t-s --scancodes\tdisplay only the raw scan-codes\n\
\t-k --keycodes\tdisplay only the interpreted keycodes (default)\n", 214},
  {"\
\n\
Press any keys - Ctrl-D will terminate this program\n\
\n", 215},
  {"press any key (program terminates 10s after last keypress)...\n", 216},
  {"release", 217},
  {"press", 218},
  {"keycode %3d %s\n", 219},
  {"%s from %s\n", 220},
};

int _msg_tbl_length = 220;
